    
    create table categoria (
       id int8 generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    );
    
    create table cliente (
       id int8 generated by default as identity,
        celular varchar(11),
        cpf varchar(11) unique,
        email varchar(255) not null unique,
        is_conta_ativa boolean,
        nome varchar(255) not null,
        senha varchar(255) not null,
        telefone varchar(11) not null,
        primary key (id)
    );
    
    create table endereco (
       id int8 generated by default as identity,
        bairro varchar(255) not null,
        cep varchar(11) not null,
        cidade varchar(255) not null,
        complemento varchar(255),
        endereco varchar(255) not null,
        numero varchar(10) not null,
        cliente_id int8 not null,
        estado_id int8 not null,
        primary key (id)
    );
    
    create table estado (
       id int8 generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    );
    
    create table funcao (
       cliente_id int8 not null,
        funcoes varchar(7) not null
    );
    
    create table item_pedido (
       desconto int4 ,
        quantidade int4 not null,
        valor float8 not null,
        pedido_id int8 not null,
        produto_id int8 not null,
        primary key (pedido_id, produto_id)
    );
    
    create table pedido (
       id int8 generated by default as identity,
        data timestamp not null,
        situacao_pagamento varchar(9) not null,
        situacao_pedido varchar(20) not null,
        valor_total float8 not null,
        cliente_id int8 not null,
        endereco_de_entrega_id int8 not null,
        primary key (id)
    );
    
    create table produto (
       id int8 generated by default as identity,
        avatar_url text,
        desconto int4,
        descricao text not null,
        is_tem_desconto boolean,
        is_tem_estoque boolean,
        nome varchar(255) not null,
        preco float8 not null,
        categoria_id int8 not null,
        primary key (id)
    );
    
    alter table if exists endereco 
       add constraint fk_endereco_cliente_id 
       foreign key (cliente_id) 
       references cliente;
    
    alter table if exists endereco 
       add constraint fk_endereco_estado_id 
       foreign key (estado_id) 
       references estado;
    
    alter table if exists funcao 
       add constraint fk_funcao_cliente_id 
       foreign key (cliente_id) 
       references cliente;
    
    alter table if exists item_pedido 
       add constraint fk_item_pedido_pedido_id 
       foreign key (pedido_id) 
       references pedido;
    
    alter table if exists item_pedido 
       add constraint fk_item_pedido_produto_id 
       foreign key (produto_id) 
       references produto;
    
    alter table if exists pedido 
       add constraint fk_pedido_cliente_id 
       foreign key (cliente_id) 
       references cliente;
    
    alter table if exists pedido 
       add constraint fk_pedido_endereco_de_entrega_id 
       foreign key (endereco_de_entrega_id) 
       references endereco;
    
    alter table if exists produto 
       add constraint fk_produto_categoria_id 
       foreign key (categoria_id) 
       references categoria;